---
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'

  ProjectName:
    Type: String
    Description: The name of this project
    Default: 'aws-news'

Resources:
  Content: ## content processing
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './content/template.yaml'
      Parameters:
        Stage: !Ref Stage
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  Services: ## API backing services
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: './services/template.yaml'
      Parameters:
        Stage: !Ref Stage
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Project
          Value: !Ref ProjectName