---
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'

  ProjectName:
    Type: String
    Description: The name of this project
    Default: 'aws-news'

Resources:
  ImageProcessingDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "aws-news-${Stage}-image-processing-dependencies"
      Description: Dependencies for aws-news image processing functions
      ContentUri: dependencies
      CompatibleRuntimes:
        - nodejs10.x
        - nodejs12.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs12.x

  EventBusNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/news/${Stage}/common/layer/image/arn"
      Type: String
      Value: !Ref ImageProcessingDependenciesLayer
      Description: Layer ARN for image processing layer
      Tags:
        Environment: !Ref Stage
        ProjectName: !Ref ProjectName