---
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'

  ProjectName:
    Type: String
    Description: The name of this project
    Default: 'aws-news'
  
  GitHubOwner:
    Type: String
    Description: GitHub repository owner username
    Default: jkahn117
  
  GitHubRepo:
    Type: String
    Description: GitHub repository for the project (name only, not URL)
    Default: aws-news
  
  GitHubBranch:
    Type: String
    Description: GitHub repository branch name (default='master')
    Default: master
  
  GitHubOAuthTokenSecretId:
    Type: String
    Description: AWS Secrets Manager Secret Id that stores Github OAuth token.
    Default: GitHubOAuthToken
  
Resources:
  PipelineApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:646794253159:applications/aws-sam-codepipeline-cd
        SemanticVersion: 1.1.0
      Parameters:
        GitHubOAuthToken: !Sub '{{resolve:secretsmanager:${GitHubOAuthTokenSecretId}}}'
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        DeployStackName: !Sub "${ProjectName}-bulid-layer-${Stage}"
        DeployRoleName: !Ref DeployRole
        DeployParameterOverrides: !Sub '{ "Stage" : "${Stage}" }'
        BuildSpecFilePath: 'backend/layer/buildspec.yaml'

  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      Description: !Sub "Deploy CloudFormation stack ${ProjectName}-bulid-layer-${Stage}. Created by CloudFormation ${AWS::StackId}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      # Minimum IAM permissions needed to deploy the layer stack
      Policies:
        - PolicyName: "deploy-change-set"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - cloudformation:CreateChangeSet
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31"
        - PolicyName: "publish-layer-version"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:PublishLayerVersion"
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer/*"
        - PolicyName: "put-parameter"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:PutParameter"
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"

Outputs:
  LayerBuildPipelineName:
    Description: Name of the layer build pipeline
    Value: !GetAtt PipelineApp.Outputs.PipelineName
