---
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'

  ProjectName:
    Type: String
    Description: The name of this project
    Default: 'aws-news'

Resources:
  LoaderDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "aws-news-${Stage}-loader-dependencies"
      Description: Dependencies for aws-news loader
      ContentUri: dependencies.zip
      CompatibleRuntimes:
        - ruby2.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Delete

  LayerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/news/${Stage}/backend/loader/layer"
      Type: String
      Value: !Ref LoaderDependencyLayer
      Description: Loader Dependency Layer ARN
      Tags:
        Environment: !Ref Stage

Outputs:
  LoaderDependencyLayerArn:
    Description: Loader Dependency Layer ARN
    Value: !Ref LoaderDependencyLayer
