---
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'
    AllowedValues:
      - 'dev'
      - 'test'
      - 'prod'

  ProjectName:
    Type: String
    Description: The name of this project
    Default: 'aws-news'

  PinpointApplicationId:
    Type: String
    Description: Application ID for Pinpoint app

Resources:
  #
  # Custom resource to create and enable a Pinpoint event stream. Custom resource is required
  # as Pinpoint is not deployed in all AWS Regions, so we need flexibility to pick the "right"
  # Region based on where Amplify has deployed Pinpoint.
  #
  EventStreamCustomResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./event-stream-resource
      Handler: custom_resource.handler
      Runtime: python3.7
      Timeout: 300
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kinesis:CreateStream
                - kinesis:DeleteStream
                - kinesis:DescribeStream
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:AttachRolePolicy
                - iam:CreateRole
                - iam:CreatePolicy
                - iam:PassRole
                - iam:DeletePolicy
                - iam:DeleteRole
                - iam:GetPolicy
                - iam:GetRole
              Resource: "*"
            - Effect: Allow
              Action:
                - mobiletargeting:PutEventStream
                - mobiletargeting:DeleteEventStream
              # allow in any region as the resource may need to be deployed elsewhere....
              Resource: !Sub "arn:aws:mobiletargeting:*:${AWS::AccountId}:apps*"
          
  PinpointEventStream:
    Type: Custom::PinpointEventStream
    Properties:
      ApplicationId: !Ref PinpointApplicationId
      ServiceToken: !GetAtt EventStreamCustomResourceFunction.Arn

  EventStreamArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/news/${Stage}/analytics/stream/arn"
      Type: String
      Value: !GetAtt PinpointEventStream.StreamArn
      Description: Analytics Event Stream ARN
      Tags:
        Environment: !Ref Stage
        Project: !Ref ProjectName
