---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'

  ProjectName:
    Type: String
    Description: The name of this project
    Default: 'aws-news'
  
  ProjectRepo:
    Type: String
    Description: GitHub repository for the project
    Default: 'https://github.com/jkahn117/aws-news.git'

Resources:
  ### ECR ###
  BuildContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectName}-build-${Stage}"
      RepositoryPolicyText:
        # Amplify Console requires "public" access
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*" # allow any AWS account, but can we tie to Amplify Console?
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
  
  ### CodeBuild ###
  BuildContainerProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-build-${Stage}"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Sub "${AWS::Region}"
          - Name: AWS_ACCOUNT_ID
            Value: !Sub "${AWS::AccountId}"
          - Name: IMAGE_REPO_NAME
            Value: !Sub "${ProjectName}-build-${Stage}"
          - Name: IMAGE_TAG
            Value: latest
      Source:
        Auth: 
          Type: OAUTH
        BuildSpec: _build/buildspec.yml
        Type: GITHUB
        Location: !Ref ProjectRepo

  ### IAM ###
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub "${ProjectName}-build-${Stage}-codebuild"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:PutImage"
                  - "ecr:UploadLayerPart"
                Resource: !GetAtt BuildContainerRepository.Arn
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"