---
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'

  ProjectName:
    Type: String
    Description: The name of this project
    Default: 'aws-news'

  ProjectRepo:
    Type: String
    Description: GitHub repository for the project
    Default: 'https://github.com/jkahn117/aws-news.git'

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket

  ### CodeBuild ###
  BuildLayerProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-build-${Stage}-layer"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: DEPLOYMENT_BUCKET_NAME
            Value: !Ref DeploymentBucket
          - Name: STACK_NAME
            Value: !Sub "${AWS::StackName}-dependencies"
          - Name: AMPLIFY_ENV
            Value: !Ref Stage
      Source:
        Auth: 
          Type: OAUTH
        BuildSpec: _build/buildspec.yml
        Type: GITHUB
        Location: !Ref ProjectRepo
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: FILE_PATH
              Pattern: backend/layer/dependencies/Gemfile
              

  ### IAM ###
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub "${ProjectName}-build-${Stage}-codebuild"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - "lambda:PublishLayerVersion"
                Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer/*
              - Effect: Allow
                Action:
                  - "ssm:PutParameter"
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*

Outputs:
  CodeBuildProject:
    Description: Name of the CodeBuild project
    Value: !Ref BuildLayerProject