---
AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: 'dev'

  ProjectName:
    Type: String
    Description: The name of this project
    Default: 'aws-news'

Resources:
  IngestionDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "aws-news-${Stage}-ingestion-dependencies"
      Description: Dependencies for aws-news ingestion functions
      ContentUri: ingestion-dependencies
      CompatibleRuntimes:
        - ruby2.7
      RetentionPolicy: Delete
      Metadata:
        BuildMethod: ruby2.7 # @see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html

  LayerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/news/${Stage}/backend/support/ingestion/layer"
      Type: String
      Value: !Ref IngestionDependenciesLayer
      Description: Ingestion Dependencies Layer ARN
      Tags:
        Environment: !Ref Stage
        ProjectName: !Ref ProjectName

Outputs:
  IngestionDependenciesLayerArn:
    Description: Loader Dependency Layer ARN
    Value: !Ref IngestionDependenciesLayer
